<?php

namespace Database\Seeders;

use App\Models\DbProducts;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DbProductsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DbProducts::firstOrCreate(
            ['name' => 'Infovegetal'],
            [
                'description' => 'Bases Infovegetal',
                'champs' => [],
                'categories' => [],
            ]
        );

        DbProducts::firstOrCreate(
            ['name' => 'Infovegetal_old'],
            [
                'description' => 'Anciennes bases Infovegetal',
                'champs' => [
                    'bc-ref' => 'sku',
                    'latin' => 'name',
                    'rem' => 'description',
                    'img' => 'img_link',
                    'fam' => 'category_products_id',
                    'ref' => 'ref',
                    'barcode' => 'ean13',
                    'pot' => 'pot',
                    'haut' => 'height',
                    'prix' => 'price',
                    'prix-etage' => 'price_floor',
                    'prix-roll' => 'price_roll',
                    'prix-promo' => 'price_promo',
                    'id-producteur' => 'producer_id',
                    'code-tva' => 'tva_id',
                    'cond' => 'cond',
                    'etage' => 'floor',
                    'roll' => 'roll',
                ],
                'categories' => [],
                'traitement' => 'infovegetal_old',
            ]
        );

        //{"prix_etage":"prix_etage","prix_cc":"prix_roll","groupe":"fam","prix_plaque":"prix"}

        DbProducts::firstOrCreate(
            ['name' => 'Eurofleurs'],
            [
                'description' => 'Bases Eurofleurs',
                'champs' => [
                    'id' => 'sku',
                    'ean' => 'ean13',
                    'article' => 'name',
                    'remarque' => 'description',
                    'prix-plaque' => 'price',
                    'image' => 'img_link',
                    'groupe' => 'category_products_name',
                    'pot' => 'pot',
                    'hauteur' => 'height',
                    'prix-etage' => 'price_floor',
                    'prix-roll' => 'price_roll',
                    'prix-promo' => 'price_promo',
                    'producteur-id' => 'producer_id',
                    'code-tva' => 'tva_id',
                    'pcs-pal' => 'cond',
                    'pal-par-etage' => 'floor',
                    'pal-par-cc' => 'roll',
                ],
                'categories' => [
                    "noel" => "51",
                    "buxus" => "26",
                    "autres" => "51",
                    "bambusa" => "31",
                    "legumes" => "19",
                    "vivaces" => "23",
                    "arbustes" => "28",
                    "bruy-res" => "51",
                    "bruyeres" => "16",
                    "fraisiers" => "20",
                    "gramin-es" => "51",
                    "graminees" => "24",
                    "hydrangea" => "51",
                    "lavandula" => "16",
                    "orchidees" => "78",
                    "hellebores" => "16",
                    "accessoires" => "39",
                    "couvres-sol" => "21",
                    "plantes-mix" => "16",
                    "compositions" => "37",
                    "jour-de-l-an" => "51",
                    "serre-froide" => "16",
                    "laurus-nobilis" => "33",
                    "plantes-vertes" => "11",
                    "sapins-de-noel" => "35",
                    "azalees-en-vert" => "10",
                    "plantes-a-bulbe" => "15",
                    "plantes-vivaces" => "23",
                    "plantes-de-haies" => "30",
                    "plantes-valorises" => "7",
                    "succulentes-sedum" => "13",
                    "coniferes-de-haies" => "29",
                    "plantes-aquatiques" => "71",
                    "plantes-grimpantes" => "17",
                    "bonsai-lucky-bambou" => "14",
                    "cactees-succulentes" => "13",
                    "plantes-d-int-rieur" => "7",
                    "plantes-d-interieur" => "96",
                    "fougeres-d-exterieur" => "22",
                    "plantes-de-p-pini-re" => "28",
                    "plantes-de-pepiniere" => "6",
                    "plantes-en-suspension" => "12",
                    "graminees-ornementales" => "24",
                    "coniferes-decorees-noel" => "35",
                    "compositions-interieures" => "36",
                    "plantes-m-diterran-ennes" => "51",
                    "plantes-mediterraneennes" => "50",
                    "ar-matiques-herbes-l-gumes" => "51",
                    "aromatiques-herbes-legumes" => "18",
                    "bulbes-jacinthes-narcissus" => "15",
                    "condimentaires-aromatiques" => "18",
                    "mediterranee-italie-espagne" => "50",
                    "pepiniere-arbustes-et-arbres" => "28",
                    "rosiers-buisson-tige-grimpant" => "32",
                    "les-fruitiers-les-petits-fruits" => "25",
                    "plantes-pour-massifs-et-balcons" => "16",
                    "plantes-fleuries-azalees-fleuries" => "10",
                    "rhodo-az-japonica-az-mollis-pieris" => "27",
                    "les-branches-coupees-2-jours-de-preavis" => "16",
                    "plantes-vivaces-commander-1-jour-avant-le-d-part" => "51",
                    "plantes-vivaces-commander-1-jour-avant-le-depart" => "51",
                    "plantes-carnivores-contactez-nous-pour-passer-commande" => "44"
                ],
                'traitement' => 'eurofleurs',
            ]
        );


        DbProducts::firstOrCreate(
            ['name' => 'Peplant'],
            [
                'description' => 'bases belges',
                'champs' => [
                    "ref" => "sku",
                    "barcode" => "ean13",
                    "leverancier" => "leverancier_peplant",
                    "min" => "contrainte_producteur",
                    "omschrijving-foto" => "name",
                    "photo-link" => "img_link",
                    "famille" => "category_products_name",
                    "remarques" => "description",
                    "pot" => "pot",
                    "hauteur" => "haut",
                    "diameter" => "diameter",
                    "emballage" => "cond",
                    "prix" => "price",
                    "prix-etage" => "prix_etage",
                    "prix-cc" => "prix_roll",
                    "promo" => "prix_promo",
                    "unite-carton" => "minimum",
                    "tags" => "tags"
                ],
                'categories' => [
                    "pepiniere-arbustes-et-arbres" => "28",
                    "condimentaires-aromatiques" => "18",
                    "vivaces" => "23",
                    "graminees-ornementales" => "24",
                    "cactees-succulentes" => "13",
                    "plantes-grimpantes" => "17",
                    "legumes" => "19",
                    "fougeres-d-exterieur" => "22",
                    "couvres-sol" => "21",
                    "fraisiers" => "20",
                    "bulbes-jacinthes-narcissus" => "15",
                    "serre-froide" => "16",
                    "plantes-fleuries-azalees-fleuries" => "10",
                    "rhodo-az-japonica-az-mollis-pieris" => "27",
                    "buxus" => "26",
                    "bambusa" => "31",
                    "rosiers-buisson-tige-grimpant" => "32",
                    "les-fruitiers-les-petits-fruits" => "25",
                    "coniferes-de-haies" => "29",
                    "plantes-vertes" => "11",
                    "plantes-en-suspension" => "12",
                    "plantes-de-haies" => "30",
                    "mediterranee-italie-espagne" => "50",
                    "bonsai-lucky-bambou" => "14",
                    "azalees-en-vert" => "10",
                    "coniferes-decorees-noel" => "35",
                    "plantes-valorises" => "7",
                    "laurus-nobilis" => "33",
                    "compositions" => "37",
                    "compositions-interieures" => "36",
                    "accessoires" => "39",
                    "orchidees" => "78",
                    "sapins-de-noel" => "35",
                    "plantes-mediterraneennes" => "50"
                ],
                'traitement' => 'peplant',
            ]
        );


        DbProducts::firstOrCreate(
            ['name' => 'DDK'],
            [
                'description' => 'bases néerlandaises, hamiplant',
                'champs' => [
                    'code' => 'sku',
                    'images' => 'img_link',
                    'description' => 'description',
                    'diametre-de-pot' => 'pot',
                    'hauteur' => 'height',
                    'qte-plaque' => 'cond',
                    'qte-etage' => 'floor',
                    'qte-cc' => 'roll',
                    'prix-plaque' => 'price',
                    'prix-etage' => 'price_floor',
                    'prix-cc' => 'price_roll',
                    'mini-de-conditionnement' => 'minimum',
                    'codebarre' => 'ean13',
                    'producteur' => 'producteur_name',
                    'cde-producteur' => 'producteur_code'
                ],
                'categories' => [
                    "plantes-fleuries" => "10",
                    "bonsai-d-extrieur" => "70",
                    "cactes-succulentes" => "13",
                    "carnivores" => "44",
                    "compositions-interieurs" => "36",
                    "plantes-aquatiques" => "71",
                    "inconnu" => "51",
                    "bulbes-en-pot" => "15",
                    "bonsai-interieur" => "14",
                    "buxus" => "26",
                    "conifres" => "28",
                    "plantes-vertes" => "11",
                    "fruitiers-et-lgumes" => "25",
                    "plantes-suspensions" => "12",
                    "tous-les-articles-de-fleuristerie" => "43",
                    "arbustes" => "28",
                    "hydrangea-hortensia-jardin" => "28",
                    "ilex" => "28",
                    "plantes-grimpantes" => "17",
                    "aromatiques" => "18",
                    "laurus-nobilis" => "33",
                    "lavandula" => "16",
                    "plantes-mditerranennes" => "50",
                    "orchides" => "78",
                    "orchides-deco" => "45",
                    "phalaenopsis" => "78",
                    "phalaenopsis-deco" => "45",
                    "plantes-de-saison" => "16",
                    "compositions-exterieures" => "37",
                    "marque-decorum" => "10",
                    "marque-eden-collection" => "13",
                    "marque-kokodama" => "12",
                    "marque-optiflor" => "78",
                    "rosiers" => "32",
                    "fougres-et-gramines-et-bambou" => "22",
                    "plantes-vivaces" => "23",
                    "bulbes" => "15",
                    "plantesvertes" => "11",
                    "mix-cc" => "16",
                    "taxus" => "28",
                    "plantes-fleuries-deco" => "7",
                    "bulbes-a-fleurs" => "15",
                    "cactus" => "13",
                    "plantes-en-suspension" => "12",
                    "bulbes-fleurs-valeur-ajout" => "15",
                    "bulbes-secs" => "15",
                    "plantes-vertes-deco" => "7",
                    "de-retour" => "51",
                    "helleborus" => "16",
                    "mini-plantes" => "11",
                    "accessoires-dcoration" => "43",
                    "compositions-exterieurs" => "37",
                    "trademark-ansu" => "45",
                    "bulbes-fleurs" => "10",
                    "bonsai-ficus-ginseng-lucky-bamboo" => "14",
                    "plantes-de-terrasses" => "16",
                    "phalaenopsis-optiflor" => "78",
                    "plantes-interieurs-deco" => "7",
                    "plantes-de-jardin-fleuri" => "16",
                    "articles-d-automne" => "16",
                    "kerst-natale-christmas" => "35",
                    "nol" => "51",
                    "thema-valentijn-valentino" => "7"
                ],
                'traitement' => 'ddk',
            ]
        );

    }
}
